# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.8

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-defaults

  - wandb>=0.10.30
  - opencv-python-headless>=4.4.0.46
  - numpy
  - matplotlib>=3.3.3
  - torch>=1.8.1
  - torch-summary
  - pandas~=1.4.1
  - azureml-core~=1.39.0
  - torchvision
  - tqdm
- pip
- python-spams
channels:
- anaconda
- conda-forge
- pytorch
- defaults
